/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikacija_sustav_natjecanja;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author valen
 */
public class FormaPitanja extends javax.swing.JFrame {
    private int brojPitanja = 0;
    /**
     * Creates new form FormaPitanja
     */
    
    public FormaPitanja() {
        initComponents();
        setLocationRelativeTo(null);
        panelpitanja.setLayout(new BoxLayout(panelpitanja, BoxLayout.Y_AXIS));
    }
    
    private static ArrayList<String> listaPitanja = new ArrayList<>();
    private static ArrayList<String> tocniOdgovori = new ArrayList<>();
    
    /*private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        dodajpitanje = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        panelpitanja = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 146, 118));
        jLabel1.setText("Definiraj pitanja");

        dodajpitanje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dodajpitanje.setText("Dodaj pitanje");
        dodajpitanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajpitanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpitanjaLayout = new javax.swing.GroupLayout(panelpitanja);
        panelpitanja.setLayout(panelpitanjaLayout);
        panelpitanjaLayout.setHorizontalGroup(
            panelpitanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        panelpitanjaLayout.setVerticalGroup(
            panelpitanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        scroll.setViewportView(panelpitanja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(dodajpitanje)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dodajpitanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dodajpitanje = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        panelpitanja = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        pitanje = new javax.swing.JTextField();
        odgovor = new javax.swing.JTextField();
        questionLabel1 = new javax.swing.JLabel();
        potvrdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 146, 118));
        jLabel1.setText("Definiraj pitanja");

        dodajpitanje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dodajpitanje.setText("Dodaj pitanje");
        dodajpitanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajpitanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpitanjaLayout = new javax.swing.GroupLayout(panelpitanja);
        panelpitanja.setLayout(panelpitanjaLayout);
        panelpitanjaLayout.setHorizontalGroup(
            panelpitanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        panelpitanjaLayout.setVerticalGroup(
            panelpitanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        scroll.setViewportView(panelpitanja);

        questionLabel.setText("Pitanje");

        questionLabel1.setText("Odgovor");

        potvrdi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        potvrdi.setText("Potvrdi");
        potvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                .addComponent(dodajpitanje))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(questionLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(odgovor, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(questionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(pitanje, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addComponent(potvrdi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dodajpitanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(potvrdi))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(questionLabel)
                            .addComponent(pitanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odgovor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionLabel1))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajpitanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajpitanjeActionPerformed
       dodajPitanje();
       String Pitanje = pitanje.getText();
       String Odgovor = odgovor.getText();
       
       if(!Pitanje.isEmpty()&& !Odgovor.isEmpty()){
           listaPitanja.add(Pitanje);
           tocniOdgovori.add(Odgovor);
       }
       else{
           System.out.println("Unesite pitanje i odgovor!");
       }
       prikazPitanja();
    }//GEN-LAST:event_dodajpitanjeActionPerformed

    public void prikazPitanja(){
        for (int i = 0; i < listaPitanja.size(); i++){
            System.out.println("Pitanje" + (i+1) + ":" + listaPitanja.get(i));
        }
    }
    
    private void potvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdiActionPerformed
        this.dispose();
    }//GEN-LAST:event_potvrdiActionPerformed
 
    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPitanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPitanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPitanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPitanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPitanja().setVisible(true);
            }
        });
    }
    private void dodajPitanje() {   
        
        brojPitanja++;
        JPanel panelpitanja = new JPanel(new GridLayout(2, 2, 5, 5));

        JLabel questionLabel = new JLabel("Pitanje " + brojPitanja + ":");
        JTextField questionField = new JTextField();
        
        JLabel answerLabel = new JLabel("Tocan odgovor " + brojPitanja + ":");
        JTextField answerField = new JTextField();

        panelpitanja.add(questionLabel);
        panelpitanja.add(questionField);
        panelpitanja.add(answerLabel);
        panelpitanja.add(answerField);

        panelpitanja.add(panelpitanja);
        panelpitanja.revalidate();
        panelpitanja.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajpitanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField odgovor;
    private javax.swing.JPanel panelpitanja;
    private javax.swing.JTextField pitanje;
    private javax.swing.JButton potvrdi;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel questionLabel1;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}
