package aplikacija_sustav_natjecanja;

import java.awt.CardLayout;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import klase.Natjecanje;
import static klase.Natjecanje.listaNatjecanja;
import static sun.util.calendar.CalendarUtils.mod;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vfuntak
 */
public class FrameHome extends javax.swing.JFrame {

    /**
     * Creates new form FrameHome
     */
    public FrameHome() {
        initComponents();
        MainCont.add("PanelPocetna", new PanelPocetna(MainCont));
        MainCont.add("PanelPregledNatjecanja", new PanelPregledNatjecanja(MainCont));
        MainCont.add("PanelSudjelovanaNatjecanja", new PanelSudjelovanaNatjecanja(MainCont));
        MainCont.add("PanelIspitNatjecanja", new PanelIspitNatjecanja(MainCont));
        MainCont.add("PanelPrethodnaNatjecanja", new PanelPrethodnaNatjecanja(MainCont));
        MainCont.add("PanelRezultati", new PanelRezultati(MainCont));
        MainCont.add("PanelObjaviNatjecanje", new PanelObjaviNatjecanje(MainCont));
        MainCont.add("PanelOdjava", new PanelOdjava(MainCont));
        
        setLocationRelativeTo(null);
    } 
    
    private void prikaziNaziveNatjecanja() {
        try (FileInputStream fileIn = new FileInputStream("C:\\Users\\valen\\OneDrive\\Documents\\NetBeansProjects\\Java_Aplikacija\\SVE\\Objavljena_natjecanja.txt");
             ObjectInputStream objectIn = new ObjectInputStream(fileIn)) {

            while (true) {
                Object obj = objectIn.readObject();
                if (obj instanceof ArrayList) {
                    ArrayList<Natjecanje> natjecanja = (ArrayList<Natjecanje>) obj;
                    for (Natjecanje natjecanje : natjecanja) {
                        String nazivNatjecanja = natjecanje.getNazivNatjecanja();
                        listaNatjecanja.add(natjecanje);
                       // mod.addElement(nazivNatjecanja);
                    }
                }
            }
        } catch (EOFException e) {
            // Do nothing, end of file reached
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainCont = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Pocetna = new javax.swing.JMenuItem();
        Pregled = new javax.swing.JMenuItem();
        Sudjelovana = new javax.swing.JMenuItem();
        Ispit = new javax.swing.JMenuItem();
        Prethodna = new javax.swing.JMenuItem();
        Rezultati = new javax.swing.JMenuItem();
        Objava = new javax.swing.JMenuItem();
        Odjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MainCont.setPreferredSize(new java.awt.Dimension(790, 590));
        MainCont.setLayout(new java.awt.CardLayout());

        jMenuBar1.setBackground(new java.awt.Color(60, 63, 65));
        jMenuBar1.setForeground(new java.awt.Color(60, 63, 65));

        jMenu1.setText("Izabornik");

        Pocetna.setText("Pocetna");
        Pocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PocetnaActionPerformed(evt);
            }
        });
        jMenu1.add(Pocetna);

        Pregled.setText("Pregled natjecanja");
        Pregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PregledActionPerformed(evt);
            }
        });
        jMenu1.add(Pregled);

        Sudjelovana.setText("Sudjelovana natjecanja");
        Sudjelovana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SudjelovanaActionPerformed(evt);
            }
        });
        jMenu1.add(Sudjelovana);

        Ispit.setText("Ispit natjecanja");
        Ispit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IspitActionPerformed(evt);
            }
        });
        jMenu1.add(Ispit);

        Prethodna.setText("Prethodna natjecanja");
        Prethodna.setToolTipText("");
        Prethodna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrethodnaActionPerformed(evt);
            }
        });
        jMenu1.add(Prethodna);

        Rezultati.setText("Rezultati");
        Rezultati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RezultatiActionPerformed(evt);
            }
        });
        jMenu1.add(Rezultati);

        Objava.setText("Objavi natjecanje");
        Objava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjavaActionPerformed(evt);
            }
        });
        jMenu1.add(Objava);

        Odjava.setText("Odjava");
        Odjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdjavaActionPerformed(evt);
            }
        });
        jMenu1.add(Odjava);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainCont, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainCont, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1039, 719);
    }// </editor-fold>//GEN-END:initComponents

    private void PocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PocetnaActionPerformed
        System.out.println("PanelPocetna otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelPocetna");
    }//GEN-LAST:event_PocetnaActionPerformed

    private void PregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PregledActionPerformed
        System.out.println("PanelPregled otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelPregledNatjecanja");
    }//GEN-LAST:event_PregledActionPerformed

    private void SudjelovanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SudjelovanaActionPerformed
        System.out.println("PanelSudjelovanaNatjecanja otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelSudjelovanaNatjecanja");
    }//GEN-LAST:event_SudjelovanaActionPerformed

    private void IspitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IspitActionPerformed
        System.out.println("PanelIspit otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelIspitNatjecanja");
    }//GEN-LAST:event_IspitActionPerformed

    private void PrethodnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrethodnaActionPerformed
        System.out.println("PanelPrethodnaNatjecanja otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelPrethodnaNatjecanja");
    }//GEN-LAST:event_PrethodnaActionPerformed

    private void RezultatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RezultatiActionPerformed
        System.out.println("PanelRezultati otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelRezultati");
    }//GEN-LAST:event_RezultatiActionPerformed

    private void ObjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjavaActionPerformed
        System.out.println("PanelObjaviNatjecanje otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelObjaviNatjecanje");
    }//GEN-LAST:event_ObjavaActionPerformed

    private void OdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdjavaActionPerformed
        System.out.println("PanelOdjava otvoren!");
        CardLayout layout = (CardLayout) MainCont.getLayout();
        layout.show(MainCont, "PanelOdjava");
    }//GEN-LAST:event_OdjavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ispit;
    private javax.swing.JPanel MainCont;
    private javax.swing.JMenuItem Objava;
    private javax.swing.JMenuItem Odjava;
    private javax.swing.JMenuItem Pocetna;
    private javax.swing.JMenuItem Pregled;
    private javax.swing.JMenuItem Prethodna;
    private javax.swing.JMenuItem Rezultati;
    private javax.swing.JMenuItem Sudjelovana;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
