/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacija_sustav_natjecanja;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import klase.Natjecanje;
import static klase.Natjecanje.prikaziNatjecanja;

/**
 *
 * @author vfuntak
 */
public class PanelPregledNatjecanja extends javax.swing.JPanel {

    private final Component parent;

    /**
     * Creates new form PanelPocetna
     *
     * @param parent
     */
    public PanelPregledNatjecanja(Component parent) {
        initComponents();
        this.parent = parent;
        UcitajPrikaziNatjecanja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultListModel mod = new DefaultListModel();

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregledNatjecanja = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(750, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 146, 118));
        jLabel1.setText("Pregled natjecanja");

        pregledNatjecanja.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pregledNatjecanja.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Trenutno nema natjecanja" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        pregledNatjecanja.setFocusable(false);
        jScrollPane1.setViewportView(pregledNatjecanja);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UcitajPrikaziNatjecanja() {
        ArrayList<Natjecanje> natjecanja = Natjecanje.prikaziNatjecanja();
        DefaultListModel<String> mod = new DefaultListModel<>();
        pregledNatjecanja.setModel(mod);
        if (natjecanja.isEmpty()) {
            mod.addElement("Nema natjecanja");
        } else {
            for (Natjecanje natjecanje : natjecanja) {
                mod.addElement(natjecanje.toString());
            }
        }
        repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> pregledNatjecanja;
    // End of variables declaration//GEN-END:variables
}
