/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacija_sustav_natjecanja;

import klase.Natjecanje;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author vfuntak
 */
public class PanelObjaviNatjecanje extends javax.swing.JPanel {

    private final Component parent;
    private String trenutnoObjavljenoNatjecanje = "";

    /**
     * Creates new form PanelPocetna
     *
     * @param parent
     */
    public PanelObjaviNatjecanje(Component parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Naslov = new javax.swing.JLabel();
        Naziv = new javax.swing.JLabel();
        naziv = new javax.swing.JTextField();
        Opis = new javax.swing.JLabel();
        pitanje1 = new javax.swing.JTextField();
        ObjaviNatjecanje = new javax.swing.JButton();
        Opis1 = new javax.swing.JLabel();
        odgovor1 = new javax.swing.JTextField();
        Opis2 = new javax.swing.JLabel();
        Opis3 = new javax.swing.JLabel();
        pitanje2 = new javax.swing.JTextField();
        odgovor2 = new javax.swing.JTextField();
        Opis4 = new javax.swing.JLabel();
        Opis5 = new javax.swing.JLabel();
        pitanje3 = new javax.swing.JTextField();
        odgovor3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Objavljeno = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        naslov = new javax.swing.JLabel();
        prikazNaziv = new java.awt.TextArea();

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Ispit natjecanja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel2)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addContainerGap(459, Short.MAX_VALUE))
        );

        jRadioButton1.setText("jRadioButton1");

        setPreferredSize(new java.awt.Dimension(750, 550));

        jPanel2.setBackground(new java.awt.Color(78, 146, 118));

        Naslov.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Naslov.setForeground(new java.awt.Color(255, 255, 255));
        Naslov.setText("Objavi natjecanje");

        Naziv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Naziv.setForeground(new java.awt.Color(255, 255, 255));
        Naziv.setText("Naziv natjecanja:");

        Opis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis.setForeground(new java.awt.Color(255, 255, 255));
        Opis.setText("1. Pitanje:");

        ObjaviNatjecanje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ObjaviNatjecanje.setForeground(new java.awt.Color(255, 255, 255));
        ObjaviNatjecanje.setText("Objavi natjecanje");
        ObjaviNatjecanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjaviNatjecanjeActionPerformed(evt);
            }
        });

        Opis1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis1.setForeground(new java.awt.Color(255, 255, 255));
        Opis1.setText("1. Odgovor:");

        Opis2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis2.setForeground(new java.awt.Color(255, 255, 255));
        Opis2.setText("2. Pitanje:");

        Opis3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis3.setForeground(new java.awt.Color(255, 255, 255));
        Opis3.setText("2. Odgovor:");

        Opis4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis4.setForeground(new java.awt.Color(255, 255, 255));
        Opis4.setText("3. Pitanje:");

        Opis5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Opis5.setForeground(new java.awt.Color(255, 255, 255));
        Opis5.setText("3. Odgovor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Naslov)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Naziv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(naziv))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pitanje1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(odgovor1)))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pitanje2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(odgovor2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pitanje3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Opis5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(odgovor3)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ObjaviNatjecanje)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Naslov)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Naziv)
                    .addComponent(naziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis)
                    .addComponent(pitanje1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis1)
                    .addComponent(odgovor1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis2)
                    .addComponent(pitanje2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis3)
                    .addComponent(odgovor2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis4)
                    .addComponent(pitanje3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opis5)
                    .addComponent(odgovor3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ObjaviNatjecanje, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(78, 80, 82));

        Objavljeno.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Objavljeno.setForeground(new java.awt.Color(78, 146, 118));
        Objavljeno.setText("Objavljena natjecanja");

        naslov.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        naslov.setForeground(new java.awt.Color(51, 153, 255));
        naslov.setText("Prikaz naziva objavljenih natjecanja:");

        prikazNaziv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        prikazNaziv.setEditable(false);
        prikazNaziv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naslov)
                    .addComponent(prikazNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naslov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prikazNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Objavljeno))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Objavljeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ObjaviNatjecanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjaviNatjecanjeActionPerformed
        String nazivNatjecanja = naziv.getText();

        ArrayList<Natjecanje> listaNatjecanja = new ArrayList<>();
        ArrayList<String> listaPitanja = new ArrayList<>();
        List<String> točniOdgovori = new ArrayList<>();

        String Pitanje1 = pitanje1.getText();
        String Odgovor1 = odgovor1.getText();
        String Pitanje2 = pitanje2.getText();
        String Odgovor2 = odgovor2.getText();
        String Pitanje3 = pitanje3.getText();
        String Odgovor3 = odgovor3.getText();

        listaPitanja.add(Pitanje1);
        listaPitanja.add(Pitanje2);
        listaPitanja.add(Pitanje3);

        točniOdgovori.add(Odgovor1);
        točniOdgovori.add(Odgovor2);
        točniOdgovori.add(Odgovor3);

        String[] točniOdgovoriArray = točniOdgovori.toArray(new String[0]);

        Natjecanje.unosNatjecanja(nazivNatjecanja, listaPitanja, točniOdgovoriArray);
        Natjecanje.spremiPodatkeUDatoteku();

        String trenutniTekst = prikazNaziv.getText();
        if (!trenutniTekst.isEmpty()) {
            trenutniTekst += "\n";
        }
        trenutniTekst += nazivNatjecanja;
        prikazNaziv.setText(trenutniTekst);
    }//GEN-LAST:event_ObjaviNatjecanjeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Naslov;
    private javax.swing.JLabel Naziv;
    private javax.swing.JButton ObjaviNatjecanje;
    private javax.swing.JLabel Objavljeno;
    private javax.swing.JLabel Opis;
    private javax.swing.JLabel Opis1;
    private javax.swing.JLabel Opis2;
    private javax.swing.JLabel Opis3;
    private javax.swing.JLabel Opis4;
    private javax.swing.JLabel Opis5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel naslov;
    private javax.swing.JTextField naziv;
    private javax.swing.JTextField odgovor1;
    private javax.swing.JTextField odgovor2;
    private javax.swing.JTextField odgovor3;
    private javax.swing.JTextField pitanje1;
    private javax.swing.JTextField pitanje2;
    private javax.swing.JTextField pitanje3;
    private java.awt.TextArea prikazNaziv;
    // End of variables declaration//GEN-END:variables
}
